# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

.build-steps: &build-steps
  steps:
    - checkout
    - run:
      name: Build project
      command: .circleci/run.sh
    - run:
      name: Trigger conan build
      command: curl --user ${CIRCLE_API_USER_TOKEN} \
                --data build_parameters[CIRCLE_JOB]=build_conan \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/mdizhas/allynet-automation/tree/circleci-project-setup
jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run: echo "We are trying to execute automation script from another repo."
      - run: node --version
  test-auto:
    docker: 
      - image: conanio/clang10
    steps:
      - checkout
      - run: sudo chmod +x .circleci/run.sh
      - run: .circleci/run.sh
      - run: curl --user ${CIRCLE_API_USER_TOKEN} \
                --data build_parameters[CIRCLE_JOB]=build_conan \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/mdizhas/allynet-automation/tree/circleci-project-setup
                
      
          
  # xcode10:
  #   steps:
  #     - checkout
  #   macos:
  #     xcode: 10.2
  #     <<: bulid-steps
  # gcc-9:
  #   docker:
  #     - image: conanio/gcc9
  #   <<: bulid-steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - test-auto

machine:
  environment:
    CIRCLE_API_USER_TOKEN: "edee14237be82c217cbd25e1b41c5e2bada40579"
    BROWSERSTACK_USERNAME: "mohammedizhas_DqiMzA"
    BROWSERSTACK_ACCESS_KEY: "FjApp8QYJfjajQsQyw6N"
    BROWSERSTACK_LOCAL: false
    BROWSERSTACK_LOCAL_IDENTIFIER: "identifier"

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#     # Inside the workflow, you define the jobs you want to run.
#     jobs:
#       - node/test:
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
#           version: '16.10'
#           # If you are using yarn, change the line below from "npm" to "yarn"
#           pkg-manager: npm


